int _putchar(char);
char *_strcat(char *dest, char *src);
char *_strcat(char*, char*);
char *_strncat(char*, char*, int);
char *_strncpy(char*, char*, int);
char *leet(char *);
int _strcmp(char*, char*);
void reverse_array(int*, int);
char *string_toupper(char*);
char *cap_string(char*);
char *rot13(char*);
void print_number(int n);
